export const SWITCHTAB_CAMPANEL = 'SWITCHTAB_CAMPANEL';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';

export const ADD_IMAGES = 'ADD_IMAGES';
export const REMOVE_IMAGES = 'REMOVE_IMAGES';
